### ISSUE TITLE
manual data download from CLI: python or python3?

### ISSUE THREAD

**Issue by anastassiavybornova** [anastassiavybornova/bike-node-planner-data-denmark#36]
In the instructions for manual download, we have 2 scripts to be run by a standalone (NOT qgis) version of python, ie by running `python <scriptname>`. for me it only worked when running `python3 <scriptname>` (i think in my case `python` is pointing to some old version of python that i installed, it's a bit of a mess). @anerv wanted to check how it looks like on your side? can you run the scripts with `python`, `python3`, or both?

**Comment by anerv** [comment]
but to avoid problems it might make sense to just always ask people to use python3?

**Comment by anastassiavybornova** [comment]
done! thanks :) @anerv
